# SPDX-FileCopyrightText: Copyright (c) 2023-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

exclude: monitor/dcgm/
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies: [toml]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        types_or: [python, cython]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args:
          [
            --max-line-length=88,
            --select=C,
            E,
            F,
            W,
            B,
            B950,
            --extend-ignore = E203,
            E501,
          ]
        types_or: [python, cython]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.5
    hooks:
      - id: clang-format
        types_or: [c, c++, cuda, proto, textproto, java]
        args: ["-fallback-style=none", "-style=file", "-i"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: ["--toml", "pyproject.toml"]
        exclude: (?x)^(.*stemmer.*|.*stop_words.*|^CHANGELOG.md$)
  - repo: local
    hooks:
      - id: add-copyright
        name: add-copyright
        entry: python tools/add_copyright.py
        language: python
        require_serial: true
  # More details about these pre-commit hooks here:
  # https://pre-commit.com/hooks.html
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
        exclude: ^helm-chart/templates\/.*$
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
        types_or: [c, c++, cuda, proto, textproto, proto, java, python, shell, bash]
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        types_or: [python, cython]
        args:
          [
            "--explicit-package-bases",
            "--ignore-missing-imports",
            "--show-error-codes",
            "--pretty",
            "--show-column-numbers",
            "--show-error-context",
            "--disable-error-code",
            "import-untyped",
          ]
        exclude: |
          (?x)^(
            examples/.*/model\.py|
            experiments/.*|
            qa/.*/.*config_generator\.py|
            qa/.*/check_results\.py|
            setup.py|
          )$
